// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5SjnKbPhd3PUW_VPaTrmYBQRv-K2hflY',
    appId: '1:750337622291:web:2e91bdfa2e26f8bc915ae6',
    messagingSenderId: '750337622291',
    projectId: 'journey-96c13',
    authDomain: 'journey-96c13.firebaseapp.com',
    storageBucket: 'journey-96c13.firebasestorage.app',
    measurementId: 'G-16XGN097JH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBabV9qhJQ8kOH9Eh_DtkTVn84NyK8qpW8',
    appId: '1:750337622291:android:7d263d60f1297c16915ae6',
    messagingSenderId: '750337622291',
    projectId: 'journey-96c13',
    storageBucket: 'journey-96c13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-rHPUJP4diyDwtHe9ouXOKBW8ApVAOPs',
    appId: '1:750337622291:ios:726e0802f7556d42915ae6',
    messagingSenderId: '750337622291',
    projectId: 'journey-96c13',
    storageBucket: 'journey-96c13.firebasestorage.app',
    androidClientId: '750337622291-46uiguesh3m8jrp7blrv3o1n4pkjfk7i.apps.googleusercontent.com',
    iosClientId: '750337622291-i1q0cpc1b54kb9rgmq4kc3orp7drbp1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.journey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-rHPUJP4diyDwtHe9ouXOKBW8ApVAOPs',
    appId: '1:750337622291:ios:726e0802f7556d42915ae6',
    messagingSenderId: '750337622291',
    projectId: 'journey-96c13',
    storageBucket: 'journey-96c13.firebasestorage.app',
    androidClientId: '750337622291-46uiguesh3m8jrp7blrv3o1n4pkjfk7i.apps.googleusercontent.com',
    iosClientId: '750337622291-i1q0cpc1b54kb9rgmq4kc3orp7drbp1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.journey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5SjnKbPhd3PUW_VPaTrmYBQRv-K2hflY',
    appId: '1:750337622291:web:6493204e5dd44c3b915ae6',
    messagingSenderId: '750337622291',
    projectId: 'journey-96c13',
    authDomain: 'journey-96c13.firebaseapp.com',
    storageBucket: 'journey-96c13.firebasestorage.app',
    measurementId: 'G-WWW30J0SZB',
  );

}